### ISSUE TITLE
Date of drinking incorrect when tab left for long in Chrome mobile

### ISSUE THREAD

**Issue by ghost** [pabueco/woah#3]
reproduce steps:
1. Load the page
2. Use another app(s) for some time >1-2min.
3. Get back to Chrome browser.
4. Tap add drink

Actual result:
see that action adds drinks x-minutes ago

Expected result:
The drink should be added with DateTime now() when clicked

**Comment by pabueco** [comment]
That's a weird one. Thanks for reporting!

**Comment by pabueco** [comment]
Should be fixed now.

**Comment by ghost** [comment]
yeah, looks like it is fixed. Thanks :)

**Comment by badaszszsz** [comment]
Also checked if time travel would make the app cry - not at all (you could have dring "in 5 minutes" if you change clock
